package UI.Admin;

import Business.AirlineBusiness;
import UI.LoginInJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    AirlineBusiness ab;


    public AdminWorkAreaJPanel(AirlineBusiness ab,JPanel mainWorkArea) {
        initComponents();
        this.ab = ab;
        this.mainWorkArea = mainWorkArea;        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        menuBar = new javax.swing.JPanel();
        btnViewFlightSchedule = new javax.swing.JButton();
        btnMngAirlineCompany = new javax.swing.JButton();
        btnManageDistributor = new javax.swing.JButton();
        btnViewAllTickets = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        splitPane.setDividerLocation(50);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menuBar.setBackground(new java.awt.Color(242, 249, 255));
        menuBar.setPreferredSize(new java.awt.Dimension(817, 100));

        btnViewFlightSchedule.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnViewFlightSchedule.setText("View Flight Schedule");
        btnViewFlightSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightScheduleActionPerformed(evt);
            }
        });

        btnMngAirlineCompany.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnMngAirlineCompany.setText("Manage Airline Company");
        btnMngAirlineCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngAirlineCompanyActionPerformed(evt);
            }
        });

        btnManageDistributor.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnManageDistributor.setText("Manage Distributor");
        btnManageDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDistributorActionPerformed(evt);
            }
        });

        btnViewAllTickets.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnViewAllTickets.setText("View All Tickets");
        btnViewAllTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllTicketsActionPerformed(evt);
            }
        });

        btnlogout.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnManageDistributor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMngAirlineCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewFlightSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnViewAllTickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewFlightSchedule)
                    .addComponent(btnMngAirlineCompany)
                    .addComponent(btnManageDistributor)
                    .addComponent(btnViewAllTickets)
                    .addComponent(btnlogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(menuBar);

        workArea.setBackground(new java.awt.Color(242, 249, 255));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDistributorActionPerformed
        // TODO add your handling code here:
        ManageDistributorJPanel mdjp = new ManageDistributorJPanel(ab,workArea);
        workArea.add("ManageDistributorJPanel",mdjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageDistributorActionPerformed

    private void btnMngAirlineCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngAirlineCompanyActionPerformed
        // TODO add your handling code here:
        ManageAirlineJPanel majp = new ManageAirlineJPanel(ab,workArea);
        workArea.add("ManageAirlineJPanel",majp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnMngAirlineCompanyActionPerformed

    private void btnViewFlightScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightScheduleActionPerformed
        // TODO add your handling code here:
        ViewFlightScheduleJPanel vfsjp = new ViewFlightScheduleJPanel(ab,workArea);
        workArea.add("ViewFlightScheduleJPanel",vfsjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnViewFlightScheduleActionPerformed

    private void btnViewAllTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllTicketsActionPerformed
        // TODO add your handling code here:
        ViewAllTicketsJPanel vatjp = new ViewAllTicketsJPanel(ab,workArea);
        workArea.add("ViewAllTicketsJPanel",vatjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnViewAllTicketsActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed

        mainWorkArea.removeAll();
        LoginInJPanel ljp = new LoginInJPanel(ab,mainWorkArea);
        mainWorkArea.add("LoginInJPanel",ljp);
        ((java.awt.CardLayout) mainWorkArea.getLayout()).next(mainWorkArea);
    }//GEN-LAST:event_btnlogoutActionPerformed



   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDistributor;
    private javax.swing.JButton btnMngAirlineCompany;
    private javax.swing.JButton btnViewAllTickets;
    private javax.swing.JButton btnViewFlightSchedule;
    private javax.swing.JButton btnlogout;
    private javax.swing.JPanel menuBar;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
