package UI.Passenger;

import Business.AirlineBusiness;
import Passenger.PassengerProfile;
import UI.Admin.ViewAllTicketsJPanel;
import UI.Faculty.*;
import UI.LoginInJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class PassengerWorkAreaJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    AirlineBusiness ab;
    PassengerProfile pp;

    public PassengerWorkAreaJPanel(AirlineBusiness ab,JPanel mainWorkArea,PassengerProfile pp) {
        initComponents();
        this.ab = ab;
        this.mainWorkArea = mainWorkArea;
        this.pp = pp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        menuBar = new javax.swing.JPanel();
        btnBookRoundTrip = new javax.swing.JButton();
        btnBookTickets = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnBookConnecting = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        splitPane.setDividerLocation(50);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menuBar.setBackground(new java.awt.Color(242, 249, 255));
        menuBar.setAutoscrolls(true);

        btnBookRoundTrip.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnBookRoundTrip.setText("Book RoundTrip Tickets");
        btnBookRoundTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookRoundTripActionPerformed(evt);
            }
        });

        btnBookTickets.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnBookTickets.setText("Book Tickets");
        btnBookTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTicketsActionPerformed(evt);
            }
        });

        btnlogout.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        btnBookConnecting.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnBookConnecting.setText("Book ConnectingTrip Tickets");
        btnBookConnecting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookConnectingActionPerformed(evt);
            }
        });

        btnOrder.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnOrder.setText("View My Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnBookTickets)
                .addGap(18, 18, 18)
                .addComponent(btnBookRoundTrip)
                .addGap(18, 18, 18)
                .addComponent(btnBookConnecting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrder)
                .addGap(18, 18, 18)
                .addComponent(btnlogout)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookRoundTrip)
                    .addComponent(btnBookTickets)
                    .addComponent(btnlogout)
                    .addComponent(btnBookConnecting)
                    .addComponent(btnOrder))
                .addContainerGap())
        );

        splitPane.setTopComponent(menuBar);

        workArea.setBackground(new java.awt.Color(242, 249, 255));
        workArea.setAutoscrolls(true);
        workArea.setSize(new java.awt.Dimension(900, 800));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(splitPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed

        mainWorkArea.removeAll();
        LoginInJPanel ljp = new LoginInJPanel(ab,mainWorkArea);
        mainWorkArea.add("LoginInJPanel",ljp);
        ((java.awt.CardLayout) mainWorkArea.getLayout()).next(mainWorkArea);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnBookTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTicketsActionPerformed
        // TODO add your handling code here:
        BookOneWayJPanel bowjp = new BookOneWayJPanel(ab,workArea,pp);
        workArea.add("BookOneWayJPanel",bowjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnBookTicketsActionPerformed

    private void btnBookRoundTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookRoundTripActionPerformed
        // TODO add your handling code here:
        BookRoundJPanel brjp = new BookRoundJPanel(ab,workArea,pp);
        workArea.add("BookRoundJPanel",brjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnBookRoundTripActionPerformed

    private void btnBookConnectingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookConnectingActionPerformed
        // TODO add your handling code here:
        BookConnectingJPanel bcjp = new BookConnectingJPanel(ab,workArea,pp);
        workArea.add("BookConncetingJPanel",bcjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnBookConnectingActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        ViewOrderJPanel vojp = new ViewOrderJPanel(ab,workArea,pp);
        workArea.add("ViewOrderJPanel",vojp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookConnecting;
    private javax.swing.JButton btnBookRoundTrip;
    private javax.swing.JButton btnBookTickets;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnlogout;
    private javax.swing.JPanel menuBar;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
