/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Airline;

import Airline.AirlineCompany;
import Business.AirlineBusiness;
import Faculty.FacultyFlightAssignment;
import Faculty.FacultyProfile;
import Flight.Flight;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author martta
 */
public class AssignFacultyJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    AirlineBusiness ab;
    AirlineCompany ac;
    /**
     * Creates new form AssignFacultyJPanel
     */
    public AssignFacultyJPanel(AirlineBusiness ab,JPanel mainWorkArea,AirlineCompany ac) {
        initComponents();
        this.ab = ab;
        this.mainWorkArea = mainWorkArea;    
        this.ac = ac;
        
        populateAvailableFacultyTable();
    }
    
    private void populateCurrentFacultyTable(Flight flight) {
        DefaultTableModel model = (DefaultTableModel) tblCurrentFaculty.getModel();
        model.setRowCount(0);

        List<FacultyFlightAssignment> assignments = ab.getffaDirectory()
            .getAssignmentsByFlightId(flight.getFlightNumber());

        for (FacultyFlightAssignment assignment : assignments) {
            FacultyProfile faculty = assignment.getFaculty();
            Object[] row = new Object[] {
                faculty.getId(),
                faculty.getName(),
                faculty.getRole()
            };
            model.addRow(row);
        }
    }
    
    private void populateAvailableFacultyTable() {
        DefaultTableModel model = (DefaultTableModel) tblAvailableFaculty.getModel();
        model.setRowCount(0);

        List<FacultyProfile> allFaculty = ab.getFacultyDirectory().getAllFaculty();

        List<FacultyFlightAssignment> allAssignments = ab.getffaDirectory().getAssignments();

        Set<String> assignedFacultyIds = allAssignments.stream()
            .map(assignment -> assignment.getFaculty().getId())
            .collect(Collectors.toSet());

        for (FacultyProfile faculty : allFaculty) {
            if (!assignedFacultyIds.contains(faculty.getId())) {
                Object[] row = new Object[] {
                    faculty.getId(),
                    faculty.getName(),
                    faculty.getRole()
                };
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFlightNumber = new javax.swing.JLabel();
        txtFlightNumber = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCurrentFaculty = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvailableFaculty = new javax.swing.JTable();
        lblCurrentFaculty = new javax.swing.JLabel();
        lblAvailableFaculty = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 249, 255));

        lblFlightNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblFlightNumber.setText("Flight Number:");

        txtFlightNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFlightNumberActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnSearch.setText("Search Flight");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblCurrentFaculty.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tblCurrentFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Work ID", "Name", "Role"
            }
        ));
        jScrollPane1.setViewportView(tblCurrentFaculty);

        btnAssign.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        tblAvailableFaculty.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tblAvailableFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Work ID", "Name", "Role"
            }
        ));
        jScrollPane2.setViewportView(tblAvailableFaculty);

        lblCurrentFaculty.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblCurrentFaculty.setText("Current Faculty:");

        lblAvailableFaculty.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblAvailableFaculty.setText("Available Faculty:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Add Faculty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnAssign))
                            .addComponent(lblAvailableFaculty)
                            .addComponent(lblCurrentFaculty)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFlightNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAssign)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFlightNumber)
                            .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))
                        .addGap(18, 18, 18)
                        .addComponent(lblCurrentFaculty)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblAvailableFaculty)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFlightNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFlightNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlightNumberActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String flightNumber = txtFlightNumber.getText();
        Flight flight = ab.getFlightDirectory().getFlightByNumber(flightNumber);

        if (flight != null) {
            populateCurrentFacultyTable(flight);
            populateAvailableFacultyTable();
        } else {
            JOptionPane.showMessageDialog(null, "Flight not found.");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedAvailableRow = tblAvailableFaculty.getSelectedRow();
        int selectedCurrentRow = tblCurrentFaculty.getSelectedRow();

        if (selectedAvailableRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a faculty from the available list.");
            return;
        }

        String flightNumber = txtFlightNumber.getText().trim();
        Flight flight = ab.getFlightDirectory().getFlightByNumber(flightNumber);
        if (flight == null) {
            JOptionPane.showMessageDialog(null, "Flight not found.");
            return;
        }

        String facultyId = (String) tblAvailableFaculty.getValueAt(selectedAvailableRow, 0);
        FacultyProfile faculty = ab.getFacultyDirectory().findFacultyById(facultyId);

        if (faculty == null) {
            JOptionPane.showMessageDialog(null, "Faculty not found.");
            return;
        }

        FacultyFlightAssignment newAssignment = new FacultyFlightAssignment(faculty, flight);
        ab.getffaDirectory().addAssignment(newAssignment);

        populateCurrentFacultyTable(flight);
        populateAvailableFacultyTable();  

        JOptionPane.showMessageDialog(null, "Faculty assigned successfully.");
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAvailableFaculty;
    private javax.swing.JLabel lblCurrentFaculty;
    private javax.swing.JLabel lblFlightNumber;
    private javax.swing.JTable tblAvailableFaculty;
    private javax.swing.JTable tblCurrentFaculty;
    private javax.swing.JTextField txtFlightNumber;
    // End of variables declaration//GEN-END:variables
}
