/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package UI.Distributor;

import Business.AirlineBusiness;
import Distributor.Distributor;
import UI.Admin.ManageAirlineJPanel;
import UI.Airline.*;
import UI.Faculty.*;
import UI.LoginInJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;



/**
 *
 * @author Rushabh
 */
public class DistributorWorkAreaJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    AirlineBusiness ab;
    Distributor dis;
    
    public DistributorWorkAreaJPanel(AirlineBusiness ab,JPanel mainWorkArea,Distributor dis) {
        initComponents();
        this.ab = ab;
        this.mainWorkArea = mainWorkArea;       
        this.dis = dis;
    }

   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        menuBar = new javax.swing.JPanel();
        btnManagePrice = new javax.swing.JButton();
        btnViewSalesreport = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        splitPane.setDividerLocation(50);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menuBar.setBackground(new java.awt.Color(242, 249, 255));

        btnManagePrice.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnManagePrice.setText("Manage Price");
        btnManagePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePriceActionPerformed(evt);
            }
        });

        btnViewSalesreport.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnViewSalesreport.setText("View Sales Report");
        btnViewSalesreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSalesreportActionPerformed(evt);
            }
        });

        btnlogout.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnManagePrice)
                .addGap(30, 30, 30)
                .addComponent(btnViewSalesreport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addGap(23, 23, 23))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManagePrice)
                    .addComponent(btnViewSalesreport)
                    .addComponent(btnlogout))
                .addContainerGap())
        );

        splitPane.setTopComponent(menuBar);

        workArea.setBackground(new java.awt.Color(242, 249, 255));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed

        mainWorkArea.removeAll();
        LoginInJPanel ljp = new LoginInJPanel(ab,mainWorkArea);
        mainWorkArea.add("LoginInJPanel",ljp);
        ((java.awt.CardLayout) mainWorkArea.getLayout()).next(mainWorkArea);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnManagePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePriceActionPerformed
        // TODO add your handling code here:         
        PriceManagementJPanel pmjp = new PriceManagementJPanel(ab,workArea,dis);
        workArea.add("PriceManagementJPanel",pmjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManagePriceActionPerformed

    private void btnViewSalesreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSalesreportActionPerformed
        // TODO add your handling code here:
        ViewSalesReportJPanel vsrjp = new ViewSalesReportJPanel(ab,workArea,dis);
        workArea.add("ViewSalesReportJPanel",vsrjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnViewSalesreportActionPerformed




   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManagePrice;
    private javax.swing.JButton btnViewSalesreport;
    private javax.swing.JButton btnlogout;
    private javax.swing.JPanel menuBar;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
